### ISSUE TITLE
missing vendor/autoload.php

### ISSUE THREAD

**Issue by LovindaAgung** [jeroendesloovere/vcard#134]
hi, i checked that there is no such folder or file. should i add autoload.php manually?, how to do that?
thank you.

**Comment by jeroendesloovere** [comment]
It is correct that there is no vendor/autoload.php.
Since such a folder will automatically be added by Composer.

Composer is a dependency package provider that allows you to easily install vendors in to your project.
Please check out the [composer](https://getcomposer.org) website.

Once you have installed composer you can simple execute the following line in your terminal:
`composer require jeroendesloovere/vcard` and it will be downloaded immediately.
